// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwhyhTt_YUM_BqaMZZvLrEGMbqLji1EU',
    appId: '1:939617822631:web:a24844c59d00863ddb7882',
    messagingSenderId: '939617822631',
    projectId: 'bsgd-academy',
    authDomain: 'bsgd-academy.firebaseapp.com',
    storageBucket: 'bsgd-academy.firebasestorage.app',
    measurementId: 'G-3G7V47SHKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3X71f9VoMFxQkR1juXbeEeE29rpldPd8',
    appId: '1:939617822631:android:c28bcae5be6d4a07db7882',
    messagingSenderId: '939617822631',
    projectId: 'bsgd-academy',
    storageBucket: 'bsgd-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLQVfyGJRB3fVri3_kB4O9c8Nb_dxZ90Y',
    appId: '1:939617822631:ios:abdacf7675069c53db7882',
    messagingSenderId: '939617822631',
    projectId: 'bsgd-academy',
    storageBucket: 'bsgd-academy.firebasestorage.app',
    iosBundleId: 'com.example.bsgdOnlineAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLQVfyGJRB3fVri3_kB4O9c8Nb_dxZ90Y',
    appId: '1:939617822631:ios:abdacf7675069c53db7882',
    messagingSenderId: '939617822631',
    projectId: 'bsgd-academy',
    storageBucket: 'bsgd-academy.firebasestorage.app',
    iosBundleId: 'com.example.bsgdOnlineAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjwhyhTt_YUM_BqaMZZvLrEGMbqLji1EU',
    appId: '1:939617822631:web:b0d4dcb1bf2b2f47db7882',
    messagingSenderId: '939617822631',
    projectId: 'bsgd-academy',
    authDomain: 'bsgd-academy.firebaseapp.com',
    storageBucket: 'bsgd-academy.firebasestorage.app',
    measurementId: 'G-83CDG3PGLB',
  );
}
